# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/SDL2.spec.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/cmake/CheckCPUArchitecture.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/cmake/macros.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/cmake/sdlchecks.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/include/SDL_config.h.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/include/SDL_revision.h.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/sdl2-config.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/SDL2/sdl2.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CMakeCheckCompilerFlagCommonPatterns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CMakeParseArguments.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CMakePushCheckState.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckCCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckCSourceRuns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckCXXCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckCXXSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckIncludeFiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckLanguage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckStructHasMember.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/FindGit.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/FindPkgConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/Internal/CheckCompilerFlag.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/Internal/CheckFlagCommonConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.28.2/share/cmake/Modules/Internal/CheckSourceRuns.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/jamespearce/gamecube/SDL/Builds/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/jamespearce/gamecube/SDL/Builds/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/usr/local/Cellar/cmake/3.28.2/bin/cmake -P /Users/jamespearce/gamecube/SDL/Builds/CMakeFiles/VerifyGlobs.cmake

/Users/jamespearce/gamecube/SDL/Builds/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.28.2/bin/cmake -S/Users/jamespearce/gamecube/SDL -B/Users/jamespearce/gamecube/SDL/Builds
